import type { Metadata } from "next";
import "./globals.css";

import Image from "next/image";
import MenuClick from "@/components/MenuClick";

// swiper styles
import "swiper/css";
import "swiper/css/scrollbar";
import Search from "@/components/Search";
import AudioPlayer from "@/components/AudioPlayer";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "بودكاست ☕ ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className="dark" dir="rtl">
      <body className="antialiased">
        <div className="bg-100 min-h-screen text-white" dir="rtl">
          {/* Header */}
          <header className="flex items-center justify-between py-4 px-2 sm:px-6  border-b border-200 fixed bg-100 z-50 w-full">
            <div className="flex items-center gap-2 lg:gap-4">
              <Image
                //Thmanyah_Logo.svg
                src="/Thmanyah_Logo.svg"
                alt="Thmanyah Logo"
                width={40}
                height={40}
                className="w-10 h-10 sm:w-12 sm:h-12 object-contain"
              />
            </div>

            <Search />

            <div className="flex items-center gap-2">
              <MenuClick
                items={[
                  {
                    label: "إعدادات",
                  },
                ]}
              />
            </div>
          </header>

          <div className="flex ">
            {/* Sidebar */}
            <aside className=" bg-200  mt-18 z-10 border-r border-200 pt-2  sm:w-50 hidden sm:block sticky min-h-screen ">
              <Nav />
            </aside>

            {/* Main Content */}
            <main className="flex-1 p-2 sm:p-6 block mt-15">
              {children} <AudioPlayer />
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
